# -- Main Menu --
[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Academic"
  pageRef = "academic"
  weight = 30

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 60
